<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>FGC_Stat_Analyzer_wpf</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\m39.TTF" />
    <None Remove="Fonts\PIXEARG_.TTF" />
    <None Remove="Queries\SmokeTest.graphql" />
    <None Remove="Queries\TournamentHeadCount.graphql" />
    <None Remove="Queries\TournamentTop8.graphql" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Queries\SearchTournamentsByOwner.graphql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Queries\GetOwnerByTournamentSlug.graphql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Queries\SmokeTest.graphql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Queries\TournamentHeadCount.graphql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Queries\TournamentTop8.graphql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CredentialManagement" Version="1.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\m39.TTF" />
    <Resource Include="Fonts\PIXEARG_.TTF" />
  </ItemGroup>

</Project>
